### ISSUE TITLE
好你，请问怎么得到https服务器的response中body的内容呢？

### ISSUE THREAD

**Issue by Whhy** [wuchangming/node-mitmproxy#16]
作者你好，请问怎么从https服务器响应的response中得到返回的内容呢？我试了很多种方法都不行。
在res.on("data", (chunk)=>{})得到的内容都是乱码。
我的目标服务器返回的是一个JSON字串，使用Fidder能看到返回的内容，但是使用您的模块不知道怎么取得response的body内容，还希望能解惑，谢谢。

**Comment by baiyuze** [comment]
你解决了吗
