### ISSUE TITLE
在浏览器的设置中查看‘’管理证书‘’，该证书已经在‘’受信任的颁发机构‘’里面，但是访问‘’https://localhost:6789‘’还是不行

### ISSUE THREAD

**Issue by Hazelnuttt** [wuchangming/node-mitmproxy#19]
它并没有反馈‘’使用了不受支持的协议‘’，只是说‘’localhost 意外终止了连接。‘’

**Comment by wuchangming** [comment]
chrome 里？
localhost比较特殊


**地址栏输入**：
```
chrome://flags/#allow-insecure-localhost
```
![image](https://user-images.githubusercontent.com/5039340/52696488-17b20800-2faa-11e9-8f64-2d7ce43992cd.png)
